server:
  port: 8083

spring:
  application:
    name: review-service
  data:
    mongodb:
      uri: mongodb://mongo-review:27017/review_db

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true