version: '3.8'
services:
  content-service:
    build: .
    container_name: content_service_container
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/film_arsivi
    networks:
      - film_network
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - film_network
networks:
  film_network:
    driver: bridge
volumes:
  mongo_data: